const sections = [
  { name:'Market Authority & Positioning', title:'Before buyers trust you, they have to understand you.', copy:'You may know exactly why your company is different. The question is whether a qualified buyer can see that difference without needing you to explain it personally.', button:'Start Section 1', questions:[
    ['How quickly can the right buyer understand what makes your company meaningfully different?',['It usually is not clear without a conversation','Someone from our team normally has to explain it','The basics are clear, but the difference is not always obvious','It is clear across most of our key buyer touchpoints','It is clear, differentiated, and consistently reinforced']],
    ['How consistently does your team communicate the same core story about the company?',['It varies depending on who is speaking','We have general ideas, but nothing formal guides the message','We have some shared language, but it is not used everywhere','We have a documented message that guides most market-facing communication','We have a documented message that is consistently used, tested, and refined']],
    ['Does your leadership have a point of view buyers would recognize as distinctly yours?',['Not really','Our point of view mostly comes out when someone asks us directly','We have a few repeatable ideas or themes','We have a clear point of view that shows up consistently','Our point of view is recognizable across the market and tied to what we want to be known for']],
    ['If a buyer moves from your website to LinkedIn to sales material, how consistent is the story they experience?',['It feels noticeably different from place to place','There are more differences than similarities','Some pieces align, but others do not','The story is mostly consistent','The positioning feels intentionally connected across the buyer journey']]]},
  { name:'Thought Leadership Production', title:'Your best thinking already exists. Does it make it out of the room?', copy:'Your expertise shows up every day in conversations, decisions, customer questions, sales calls, and industry observations. This section looks at whether that thinking is captured and turned into something buyers can experience before they speak with you.', button:'Start Section 2', questions:[
    ['How often is founder or executive expertise intentionally captured in a reusable format?',['Almost never','A few times a year','Occasionally, roughly monthly or less','At least a couple of times each month','We have a consistent recurring cadence'],'Think podcast, video, interview, recorded conversation, voice note, or another format that can continue working after the conversation ends.'],
    ['What usually has to happen before your expertise becomes market-facing content?',['Nothing happens unless the founder creates it personally','The founder usually has to prompt or drive the process','The team has an informal process, but it is inconsistent','There is a repeatable workflow with clear ownership','There is a repeatable workflow with clear ownership, timing, and accountability']],
    ['Once you have a strong conversation or piece of insight, how much additional value do you get from it?',['It usually ends there','It may become one or two additional pieces','We repurpose good material sometimes','Strong conversations consistently become several useful assets','One strong conversation is systematically turned into multiple assets across channels and buyer touchpoints']],
    ['How closely is your thought leadership connected to the problems buyers actually bring into sales conversations?',['Rarely','Sometimes, but mostly by accident','It is a mix of buyer-relevant and general topics','Most topics connect directly to buyer and business priorities','Buyer questions, sales conversations, and business priorities consistently shape what we publish']]]},
  { name:'Distribution', title:'Strong expertise cannot build confidence if the right buyers never encounter it.', copy:'Creating the asset is only the beginning. This section looks at whether your expertise consistently travels beyond the place where it was originally created.', button:'Start Section 3', questions:[
    ['Across how many channels does your leadership expertise show up consistently?',['None consistently','One primary channel','Two channels','Three channels','Four or more coordinated channels']],
    ['After a strong piece of content is created, is there a clear plan for where it goes next?',['No','Rarely','Sometimes','Usually','Always, with the content adapted for the channel rather than simply reposted']],
    ['How often do relationships help extend the reach of your expertise?',['Never','Rarely','Occasionally','Regularly','Relationship-based amplification is intentionally built into our distribution'],'Think guests, partners, clients, associations, industry peers, or other trusted networks.'],
    ['Who makes sure your visibility stays active after something is published?',['No one clearly owns it','The founder handles most of it','Responsibility is shared and sometimes unclear','A dedicated person or partner owns publishing and engagement','A dedicated owner follows a defined process for publishing, engagement, and follow-through']]]},
  { name:'Discoverability', title:'Buyers cannot trust expertise they cannot find.', copy:'Prospects are researching before the first call. This section looks at whether credible evidence of your expertise appears when they search your company, your people, your category, and the problems you solve.', button:'Start Section 4', questions:[
    ['How intentionally are you improving the way buyers find your company and expertise through search?',['We are not','We have basic website SEO, but little beyond that','We optimize occasionally','We have an ongoing search strategy','Search is actively managed and connected to our content and performance data']],
    ['How much attention are you giving to how your expertise appears in AI-driven search and answer platforms?',['None','We are aware of it but have not acted','We have done limited testing','We are actively optimizing for AI and answer-engine visibility','We actively optimize, monitor, and refine how our expertise appears in those environments']],
    ['How consistently are your podcast, video, and long-form assets optimized so buyers can actually find them?',['They generally are not optimized','It depends on the asset','We use basic optimization','Titles, descriptions, metadata, and supporting pages are consistently optimized','Optimization is consistent and informed by search or performance data']],
    ['How often do you look at what a buyer actually sees when they search for your company, leaders, category, or key problems?',['Never','Rarely','Occasionally','Regularly','Regularly, and what we find leads to specific actions']]]},
  { name:'Conversion', title:'Credibility only helps the business if buyers know what to do with it.', copy:'A prospect can understand you, trust you, and still disappear if there is no clear next step. This section looks at whether visibility is actually connected to a buyer journey.', button:'Start Section 5', questions:[
    ['When buyers engage with your expertise, how clear is the next step?',['There usually is not one','A next step appears occasionally','Some content has a next step, some does not','Most content gives the right buyer a clear next action','We intentionally match next steps to where the buyer is in the journey']],
    ['How intentionally are you capturing interest from buyers who are not ready to talk yet?',['We are not','We mostly rely on a contact form','We have one or two lead-capture opportunities','We have multiple defined ways for buyers to raise their hand','Lead capture is integrated across campaigns, content, and buyer intent']],
    ['What happens after someone raises their hand?',['Nothing consistent','Someone follows up manually when possible','We have basic automated follow-up','We have defined nurture sequences','Follow-up changes based on what the prospect did and where they are in the buyer journey']],
    ['How clearly can you see whether visibility is influencing real sales conversations?',['We cannot','Mostly through anecdotes','We can connect some activity manually','We review visibility and pipeline influence regularly','We have reliable reporting that connects engagement to sales or pipeline activity']]]},
  { name:'Execution & Consistency', title:'The system should keep moving even when you are not the one pushing it.', copy:'This is where founder dependency becomes visible. A strong system should preserve the founder’s voice and expertise without requiring the founder to personally drive every step.', button:'Start Final Section', questions:[
    ['Who owns your visibility system day to day?',['No one clearly owns it','The founder owns most of it','Responsibility is shared across several people','A dedicated internal person or partner owns it','An accountable team owns it with clearly defined roles']],
    ['How far ahead is your visibility and content activity actually planned?',['It is mostly reactive','We plan when something comes up','We usually have a short-term plan','We consistently plan at least 30 days ahead','We work from a 60 to 90 day plan tied to current business priorities']],
    ['What happens to execution when the founder becomes unavailable?',['It stops','It usually slows down significantly','Some things continue, but key pieces stall','Most of the system continues','The system continues reliably without the founder having to drive every step']],
    ['How consistently do you look at what is working and adjust your visibility strategy?',['We do not','Mostly when something goes wrong','Irregularly or a few times a year','We review performance monthly','We review monthly and make documented decisions about what to change next']]]}
];

const questions=sections.flatMap((section,sectionIndex)=>section.questions.map((q)=>({sectionIndex,category:section.name,text:q[0],choices:q[1],help:q[2]})));
const form=document.querySelector('#survey-form'),welcome=document.querySelector('[data-screen="welcome"]'),results=document.querySelector('[data-screen="results"]'),progressWrap=document.querySelector('.progress-wrap'),actions=document.querySelector('.survey-actions');
let current=0;const answers=Array(questions.length).fill(null);
sections.forEach((section,index)=>{const panel=document.createElement('section');panel.className='screen transition-screen';panel.dataset.transition=String(index);panel.innerHTML=`<p class="kicker">SECTION ${index+1} OF 6 · ${section.name}</p><h2>${section.title}</h2><p>${section.copy}</p><small>4 questions</small><button class="primary section-start" type="button" data-section="${index}">${section.button}<span>→</span></button>`;form.append(panel);section.questions.forEach((question,qIndex)=>{const globalIndex=index*4+qIndex,field=document.createElement('fieldset');field.className='screen question';field.dataset.question=String(globalIndex);field.innerHTML=`<legend><span>${section.name} · Question ${globalIndex+1}</span>${question[0]}${question[2]?`<small>${question[2]}</small>`:''}</legend><div class="choices">${question[1].map((label,i)=>`<label><input type="radio" name="question-${globalIndex}" value="${i}"><span class="choice-number">${'ABCDE'[i]}</span><span class="choice-copy"><strong>${label}</strong></span><span class="check">✓</span></label>`).join('')}</div>`;form.append(field)})});
const screens=[...document.querySelectorAll('.screen')];
function activate(selector){screens.forEach(s=>s.classList.remove('active'));document.querySelector(selector).classList.add('active')}
function showTransition(sectionIndex){activate(`[data-transition="${sectionIndex}"]`);progressWrap.hidden=true;actions.hidden=true}
function showQuestion(index){current=Math.max(0,Math.min(index,23));activate(`[data-question="${current}"]`);progressWrap.hidden=false;actions.hidden=false;document.querySelector('#progress-label').textContent=`Question ${current+1} of 24`;const percent=Math.round(((current+1)/24)*100);document.querySelector('#progress-percent').textContent=`${percent}%`;document.querySelector('#progress-bar').style.width=`${percent}%`}
function selectAnswer(value){answers[current]=Number(value);form.querySelector(`[name="question-${current}"][value="${value}"]`).checked=true;setTimeout(()=>{if(current===23)showResults();else if((current+1)%4===0)showTransition((current+1)/4);else showQuestion(current+1)},220)}
function showResults(){activate('[data-screen="results"]');progressWrap.hidden=true;actions.hidden=true;const raw=answers.reduce((a,b)=>a+b,0),score=Math.round(raw/96*100),dimensionScores=sections.map((_,i)=>Math.round(answers.slice(i*4,i*4+4).reduce((a,b)=>a+b,0)/16*100)),high=Math.max(...dimensionScores),low=Math.min(...dimensionScores),bands=score<40?['Expertise Trapped','Your expertise is stronger than the system carrying it.','Start by freeing your strongest thinking from founder-only conversations and making your market position easier to recognize.']:score<60?['Visible but Fragmented','Your expertise is visible, but the system around it is fragmented.','You have useful pieces in motion. Connecting ownership, distribution, discoverability, and next steps will help them compound.']:score<80?['Emerging Visibility Engine','Your Visibility Engine is taking shape.','The foundations are working. Strengthen the lowest-scoring dimension to turn consistent activity into compounding authority.']:['Compounding Market Authority','Your Visibility Engine is built to compound.','Your positioning, expertise, distribution, discoverability, conversion, and execution are working as a connected system.'];document.querySelector('#score-value').textContent=score;document.querySelector('.score-ring').style.setProperty('--score',score);document.querySelector('#strong-area').textContent=sections[dimensionScores.indexOf(high)].name;document.querySelector('#weak-area').textContent=sections[dimensionScores.indexOf(low)].name;document.querySelector('#result-label').textContent=bands[0];document.querySelector('#result-title').textContent=bands[1];document.querySelector('#result-copy').textContent=bands[2];document.querySelector('#dimension-results').innerHTML=sections.map((s,i)=>`<div><span>${s.name}</span><b>${dimensionScores[i]}%</b><i><em style="width:${dimensionScores[i]}%"></em></i></div>`).join('')}
function reset(){answers.fill(null);form.reset();current=0;activate('[data-screen="welcome"]');progressWrap.hidden=true;actions.hidden=true}
document.querySelector('#start-button').addEventListener('click',()=>showTransition(0));form.addEventListener('click',e=>{if(e.target.closest('.section-start'))showQuestion(Number(e.target.closest('.section-start').dataset.section)*4)});form.addEventListener('change',e=>{if(e.target.matches('input[type=radio]'))selectAnswer(e.target.value)});document.querySelector('#back-button').addEventListener('click',()=>current===0?showTransition(0):showQuestion(current-1));document.querySelector('#restart-button').addEventListener('click',reset);document.addEventListener('keydown',e=>{if(!form.querySelector(`[data-question="${current}"]`)?.classList.contains('active'))return;const i='abcde12345'.indexOf(e.key.toLowerCase())%5;if(i>=0)selectAnswer(i)});if(new URLSearchParams(location.search).has('embed'))document.body.classList.add('embedded');
